---COM_COL
---Is a function to get common column names between two view, potentially for a join
---@DNAME1= 'Database name 1'
---@TNAME1= 'Table name 1'
---@DNAME2= 'Database name 2'
---@TNAME2= 'Table name 2'

CREATE MACRO COMMON_COLUMNS (EDW_DATABASE_1 VARCHAR(100),EDW_TABORVIEW_1 VARCHAR(100), EDW_DATABASE_2 VARCHAR(100),EDW_TABORVIEW_2 VARCHAR(100)) AS 
		(
		SELECT 
			COLUMNNAME AS DIM
		FROM DBC.COLUMNS
		WHERE DATABASENAME= :EDW_DATABASE_1
		AND TABLENAME= :EDW_TABORVIEW_1

INTERSECT

		SELECT 
			COLUMNNAME AS DIM
		FROM DBC.COLUMNS
		WHERE DATABASENAME= :EDW_DATABASE_2
		AND TABLENAME= :EDW_TABORVIEW_2;
		)
		
EXEC COMMON_COLUMNS ( 'XXXDATABASE1', 'XXXTABLENAME1', 'XXXDATABASE2','XXXTABLENAME2')