--This function can be used to identify the views tables or macros created by you
CREATE MACRO PRINT_REM_MY_CONTENT (EDW_DATABASE VARCHAR(100), EDW_DATABASE_LIKE VARCHAR(100), MY_DATABASE VARCHAR(100)) AS

(
SELECT
			BASE.*
,			CASE 
					WHEN BASE.TABLEKIND = 'M' THEN 'DROP MACRO' || '  ' || TRIM(BASE.MY_CONTENT) || ';'	
					WHEN BASE.TABLEKIND = 'T' THEN 'DROP TABLE' || '  ' || TRIM(BASE.MY_CONTENT) || ';'	 
					WHEN BASE.TABLEKIND = 'V' THEN 'DROP VIEW' || '  ' || TRIM(BASE.MY_CONTENT) || ';'	
			END AS QUERYS 		
FROM	
					
			(
			SELECT
						BASE_1.TABLEKIND
			,			BASE_1.TABLENAME AS MY_CONTENT
			FROM DBC.TABLES AS  BASE_1
			WHERE BASE_1.DATABASENAME =  :EDW_DATABASE--'PROD_CE_WORK_SPACE'
			AND MY_CONTENT LIKE :EDW_DATABASE_LIKE -- 'OGTEST%'

UNION ALL

			SELECT
						BASE_2.TABLEKIND
			,			BASE_2.TABLENAME AS MY_CONTENT
			FROM DBC.TABLES AS BASE_2
			WHERE BASE_2.DATABASENAME = :MY_DATABASE  -- 'NOGL1'
			) AS BASE

;)

EXEC PRINT_REM_MY_CONTENT('XXXDATATBASENAME', 'XXXTABLENAME%', 'XXXID')